[package]
name = "k8s_update_service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.6.4"
fast_log = "1.6.10"
log = "0.4.20"

serde = {version = "1.0.192", features = ["derive"]}
serde_json = "1.0.108"
tokio = {version = "1.34.0", features = ["full"]}
tokio-util = "0.7.10"