[package]
edition = "2021"
name = "kaibai_user_service"
version = "0.1.0"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4"
fast_log = "1.6.10"
log = "0.4.20"
env = "0.1.0"

serde = {version = "1.0.192", features = ["derive"]}
serde_json = "1.0.108"
tokio = {version = "1.34.0", features = ["full"]}
tokio-util = "0.7.10"

utoipa = {version = "5.2.0", features = ["actix_extras"]}
utoipa-actix-web = "0.1"
utoipa-scalar = {version = "0.2.0", features = ["actix-web"]}


rbs = { version = "4.5"}
rbatis = { version = "4.5"}
rbdc-mysql = "4.5.0"
