[package]
edition = "2021"
name = "k8s_update_service"
version = "0.1.0"

[dependencies]
actix-cors = "0.6.4"
actix-web = "4"
fast_log = "1.6.10"
log = "0.4.20"

serde = {version = "1.0.192", features = ["derive"]}
serde_json = "1.0.108"
tokio = {version = "1.34.0", features = ["full"]}
tokio-util = "0.7.10"

utoipa = {version = "5.2.0", features = ["actix_extras"]}
utoipa-actix-web = "0.1"
# utoipa-rapidoc = {version = "5.0.0", features = ["actix-web"]}
# utoipa-redoc = {version = "5.0.0", features = ["actix-web"]}
utoipa-scalar = {version = "0.2.0", features = ["actix-web"]}
# utoipa-swagger-ui = {version = "8", features = ["actix-web"]}
